name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # This will use your secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # This will use your secret

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sakshikiran/cicd-web-app:latest  # Your Docker Hub username

      # The Deploy to Server step can be commented out for now
      # - name: Deploy to Server
      #   run: |
      #     ssh your-actual-username@your-server-ip "docker pull sakshikiran/cicd-web-app:latest && docker run -d -p 3001:80 sakshikiran/cicd-web-app:latest"
